### ISSUE TITLE
Downloaded docsearch, not sure how to get it up and running?

### ISSUE THREAD

**Issue by ghost** [jcaguirre89/docsearch#1]
I have docker downloaded on windows 10, but am not sure how to get your program up and running.
I am a total newbie with docker and programming but I'm in desperate need of a full-text pdf searchable index.

I'd be happy to pay for your assistance with this.

**Comment by jcaguirre89** [comment]
Hi @alih1029 , Thank you for your interest in this project. However, it's still very much a work in progress, and I suggest you take a look at [ambar](ambar.cloud) for something complete and functional. Be advised that I wasn't able to get it running locally, which is what motivated me to build my own, but they have some paid options that I'd assume make it easier. 

In any case, you should be able to run this project with docker by cloning the repo, `cd`'ing into the dir and running `docker-compose up --build`. That would start the OCR server, which you can visit at `localhost:5001/docs` . Because there isn't a front end yet, you can still play around with the OCR API by uploading files to localhost:8000/upload-pdf and watching the response, but there's not much more you can do for now
